-- CREATE USER SQL
CREATE USER BAD115 IDENTIFIED BY grupo02;

-- USER SQL
ALTER USER "BAD115"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- ROLES
ALTER USER "BAD115" DEFAULT ROLE "CONNECT","RESOURCE";

-- QUOTAS
ALTER USER "BAD115" QUOTA UNLIMITED ON USERS;

-- SYSTEM PRIVILEGES
GRANT CREATE DATABASE LINK TO "BAD115";
GRANT SELECT, INSERT, UPDATE, DELETE TO "BAD115";
GRANT CREATE SESSION, CREATE SEQUENCE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,CREATE SYNONYM,
      ALTER SESSION, ALTER ANY SEQUENCE, ALTER ANY TABLE, ALTER ANY PROCEDURE,
      DROP ANY TABLE, DROP ANY SEQUENCE, DROP ANY VIEW, DROP ANY PROCEDURE,DROP ANY SYNONYM TO "BAD115";

